# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2b9e92041763055584b306ea143eea79a1b5322bb2d529a39aa8a9b0186262c3bb295ba774cfa77fbc9ba09cf689b9ece88fa350b5ce9bd0d37efa5575a3bfc

test:
  secret_key_base: 6d9e8c2b14333558a46563d7558b50958fab019da6e77fa8881119b79d9c665d858b091942d7602c45d026496e6d89a6ca389b09f60c54f251db4c66634aff99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
